# Generated by Django 3.1.2 on 2021-07-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commlion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='ProjectImage/'),
        ),
        migrations.AlterField(
            model_name='qnapost',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='QnaImage/'),
        ),
    ]
