# Generated by Django 3.2 on 2021-07-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commlion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
