# Generated by Django 3.2 on 2021-07-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commlion', '0002_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='count',
        ),
    ]
