# Generated by Django 3.1.2 on 2021-07-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commlion', '0002_auto_20210701_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionpost',
            name='session_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
