# Generated by Django 3.2.5 on 2021-07-02 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commlion', '0003_auto_20210702_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
