# Generated by Django 3.2 on 2021-07-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commlion', '0003_auto_20210702_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='file',
        ),
    ]
