# Generated by Django 3.2 on 2021-07-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commlion', '0004_free'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Free',
        ),
    ]
